import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Hermes',
  description: 'Generated by create next app',
};

export default function RootLayout(
  { children }
) 
{
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Img/logo.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`bg-white text-black font-sans ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
